services:
  traefik:
    image: traefik:v2.5
    container_name: pwopryo_traefik_dev
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
      - '5050:5050'
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml
      - ./traefik/certs:/etc/certs
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.pwopryo.dev`)"
      - "traefik.http.routers.traefik.entrypoints=web,websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      
  # The backend service
  api:
    image: pwopryo/api_dev:latest
    container_name: pwopryo_api_dev
    depends_on:
      - db
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.backend.rule=Host(`api.pwopryo.dev`)'
      - 'traefik.http.routers.backend.entrypoints=web'
      - 'traefik.http.routers.backend.middlewares=redirectscheme'
      - 'traefik.http.routers.backend-secure.rule=Host(`api.pwopryo.dev`)'
      - 'traefik.http.routers.backend-secure.entrypoints=websecure'
      - 'traefik.http.routers.backend-secure.tls.certresolver=myresolver'
      - 'traefik.http.services.backend-secure.loadbalancer.server.port=3333'
      - 'traefik.http.middlewares.redirectscheme.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.redirectscheme.redirectscheme.permanent=true'
      - 'traefik.docker.network=inbound'
      restart_policy:
        condition: on-failure

  # The pgadmin service
  pgadmin:
    image: dpage/pgadmin4
    container_name: pwopryo_pgadmin_dev
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: 
      PGADMIN_DEFAULT_PASSWORD: 
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.pgadmin.rule=Host(`pgadmin.pwopryo.dev`)'
      - 'traefik.http.routers.pgadmin.entrypoints=web'
      - 'traefik.http.routers.pgadmin.middlewares=redirectscheme'
      - 'traefik.http.routers.pgadmin-secure.rule=Host(`pgadmin.pwopryo.dev`)'
      - 'traefik.http.routers.pgadmin-secure.entrypoints=websecure'
      - 'traefik.http.routers.pgadmin-secure.tls.certresolver=myresolver'
      - 'traefik.http.services.pgadmin-secure.loadbalancer.server.port=80'
      - 'traefik.http.middlewares.redirectscheme.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.redirectscheme.redirectscheme.permanent=true'
      - 'traefik.docker.network=inbound'
      restart_policy:
        condition: on-failure

  # The database service
  db:
    image: postgres:13
    container_name: pwopryo_db_dev
    environment:
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
  prometheus_data: {}
  grafana_data: {}
